
GET http://localhost:5048/projects/3

###
http://localhost:5048/projects/2


###
POST http://localhost:5048/projects
Content-Type: application/json

{
    "name": "Riad",
    "genre": "pagol",
    "price": 90.01,
    "releaseDate": "1991-07-15"
}

###
PUT http://localhost:5048/projects/4
Content-Type: application/json

{ 
    "name":"Laptop",
    "genre":"My Best Best Latopt.!",
    "price": 30.99,
    "releaseDate": "1995-07-15"
}

###
DELETE  http://localhost:5048/projects/3